/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdateProfileRouteImport } from './routes/update-profile'
import { Route as ItemRouteImport } from './routes/item'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as MainSearchRouteImport } from './routes/_main/search'
import { Route as MainProfileRouteImport } from './routes/_main/profile'
import { Route as MainHistoryRouteImport } from './routes/_main/history'
import { Route as MainFavoriteRouteImport } from './routes/_main/favorite'

const UpdateProfileRoute = UpdateProfileRouteImport.update({
  id: '/update-profile',
  path: '/update-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemRoute = ItemRouteImport.update({
  id: '/item',
  path: '/item',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MainSearchRoute = MainSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainHistoryRoute = MainHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MainRoute,
} as any)
const MainFavoriteRoute = MainFavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/item': typeof ItemRoute
  '/update-profile': typeof UpdateProfileRoute
  '/favorite': typeof MainFavoriteRoute
  '/history': typeof MainHistoryRoute
  '/profile': typeof MainProfileRoute
  '/search': typeof MainSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/item': typeof ItemRoute
  '/update-profile': typeof UpdateProfileRoute
  '/favorite': typeof MainFavoriteRoute
  '/history': typeof MainHistoryRoute
  '/profile': typeof MainProfileRoute
  '/search': typeof MainSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/item': typeof ItemRoute
  '/update-profile': typeof UpdateProfileRoute
  '/_main/favorite': typeof MainFavoriteRoute
  '/_main/history': typeof MainHistoryRoute
  '/_main/profile': typeof MainProfileRoute
  '/_main/search': typeof MainSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/item'
    | '/update-profile'
    | '/favorite'
    | '/history'
    | '/profile'
    | '/search'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/item'
    | '/update-profile'
    | '/favorite'
    | '/history'
    | '/profile'
    | '/search'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/'
  id:
    | '__root__'
    | '/_main'
    | '/auth'
    | '/item'
    | '/update-profile'
    | '/_main/favorite'
    | '/_main/history'
    | '/_main/profile'
    | '/_main/search'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ItemRoute: typeof ItemRoute
  UpdateProfileRoute: typeof UpdateProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-profile': {
      id: '/update-profile'
      path: '/update-profile'
      fullPath: '/update-profile'
      preLoaderRoute: typeof UpdateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item': {
      id: '/item'
      path: '/item'
      fullPath: '/item'
      preLoaderRoute: typeof ItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/search': {
      id: '/_main/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainSearchRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/history': {
      id: '/_main/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof MainHistoryRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/favorite': {
      id: '/_main/favorite'
      path: '/favorite'
      fullPath: '/favorite'
      preLoaderRoute: typeof MainFavoriteRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainFavoriteRoute: typeof MainFavoriteRoute
  MainHistoryRoute: typeof MainHistoryRoute
  MainProfileRoute: typeof MainProfileRoute
  MainSearchRoute: typeof MainSearchRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainFavoriteRoute: MainFavoriteRoute,
  MainHistoryRoute: MainHistoryRoute,
  MainProfileRoute: MainProfileRoute,
  MainSearchRoute: MainSearchRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ItemRoute: ItemRoute,
  UpdateProfileRoute: UpdateProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
